In [6]:
%%capture
%run data.ipynb
import time as t
import warnings
warnings.filterwarnings("ignore")

Most of the utility functions are implemented in 'utils.ipynb'. Data set is described in 'data.ipynb'.

# Delta hedging (portfolio of options)

When delta hedging a portfolio of options two cases are considered:
* When the underlying is the same for all of the options in the portfolio

$$\Delta = \frac{\partial P}{\partial S}= \frac{\partial}{\partial S}\bigg(w_1C_t^1+w_2C_t^2+...+w_KC_t^K \bigg)=\sum_{i=1}^Kw_i\Delta_i$$

where $P=$ portfolio of options, $w_i=$ weight of option i, $C_t^i=$ price of i at time t and $\Delta_i=$ delta of options i

* When the underlying is not the same

### Data

Lets condsider call options on S&P 500 maturing at 19.2.2010.

In [7]:
isx19022010C = get_sheet('isx19022010C')
isx19022010C.head()

,days_to_mat,340,345,350,355,360,365,370,375,380,...,540,545,550,555,560,565,570,sp500_spot,rf,date
0,86,152.20,NaN,NaN,NaN,132.60,NaN,NaN,NaN,113.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,491.34,0.11,21.9.2009
1,85,155.05,NaN,NaN,NaN,135.35,NaN,NaN,NaN,115.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,494.35,0.11,22.9.2009
2,84,152.40,NaN,NaN,NaN,132.70,NaN,NaN,NaN,113.30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,490.36,0.11,23.9.2009
3,83,147.00,NaN,NaN,NaN,127.25,NaN,NaN,NaN,108.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,486.99,0.11,24.9.2009
4,82,145.55,NaN,NaN,NaN,125.95,NaN,NaN,NaN,106.75,...,3.8,NaN,NaN,NaN,1525.0,NaN,NaN,484.11,0.11,25.9.2009

### Butterfly

Long $E_1 = A$ and $E_2= B$, short $E_3=(A+B)/2$